version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data

  web:
    build: .
    command: ./bin/dev
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.development
    environment:
      PHOTO_APP_DATABASE_HOST: db
      RAILS_ENV: development
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    tty: true
    stdin_open: true
    volumes:
      - .:/rails