version: '3.8'
services:
  db:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    environment:
      PHOTO_APP_DATABASE_USERNAME: postgres
      PHOTO_APP_DATABASE_PASSWORD: password
      PHOTO_APP_DATABASE_NAME: photo_app_development
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data

  web:
    build: .
    command: ./bin/dev
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      PHOTO_APP_DATABASE_USERNAME: postgres
      PHOTO_APP_DATABASE_PASSWORD: password
      PHOTO_APP_DATABASE_HOST: db
      RAILS_ENV: development
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    tty: true
    volumes:
      - .:/rails